import 'package:flutter/widgets.dart';
import 'gallery_entry.dart';
import '../components/chrome/status_bar.dart';
import '../components/chrome/home_indicator.dart';
import '../components/atoms/button.dart';
import '../components/atoms/checkbox.dart';
import '../components/atoms/toggle.dart';
import '../components/atoms/icon_button.dart';
import '../components/atoms/select_box.dart';
import '../components/atoms/thumbs_up.dart';
import '../components/atoms/translate_toggle.dart';
import '../components/atoms/progress_bar.dart';
import '../components/atoms/dim.dart';
import '../components/molecules/input_field.dart';
import '../components/molecules/text_area.dart';
import '../components/molecules/dropdown.dart';
import '../components/molecules/field_validation.dart';
import '../components/molecules/country_select.dart';
import '../components/molecules/select_card.dart';
import '../components/molecules/card_line.dart';
import '../components/molecules/card_box.dart';
import '../components/molecules/card_alarm.dart';
import '../components/molecules/chat_bubble.dart';
import '../components/molecules/avatar_card.dart';
import '../components/molecules/pronunciation_result.dart';
import '../components/organisms/gnb.dart';
import '../components/organisms/bottom_nav_bar.dart';
import '../components/organisms/dialog_basic.dart';
import '../components/organisms/dialog_share_profile.dart';
import '../components/organisms/bottom_sheet.dart';
import '../components/organisms/bottom_sheet_document.dart';
import '../components/organisms/bottom_sheet_avatar.dart';
import '../components/organisms/bottom_sheet_country_select.dart';
import '../components/organisms/bottom_sheet_alarm_settings.dart';
import '../components/organisms/bottom_sheet_feedback.dart';
import '../components/molecules/hero_avatar.dart';
import '../components/atoms/mic_button.dart';
import '../components/atoms/record_circle_button.dart';
import '../components/molecules/rating_button.dart';
import '../components/molecules/otp_input.dart';
import '../screens/mypage/avatar_detail.dart';

/// The component gallery registry. The CEO wires each component's demo here as
/// it lands (agents build the widgets; they do NOT edit this file).
const List<GalleryEntry> galleryEntries = <GalleryEntry>[
  // ── chrome ──
  GalleryEntry(group: 'chrome', title: 'StatusBar', node: '160:79547', builder: _statusBar),
  GalleryEntry(group: 'chrome', title: 'HomeIndicator', node: '160:79588', builder: _homeIndicator),
  // ── atoms ──
  GalleryEntry(group: 'atoms', title: 'Button', node: '45:45158', builder: _button),
  GalleryEntry(group: 'atoms', title: 'Checkbox', node: '175:11455', builder: _checkbox),
  GalleryEntry(group: 'atoms', title: 'Toggle', node: '175:11388', builder: _toggle),
  GalleryEntry(group: 'atoms', title: 'IconButton', node: '176:13875', builder: _iconButton),
  GalleryEntry(group: 'atoms', title: 'SelectBox', node: '170:9634', builder: _selectBox),
  GalleryEntry(group: 'atoms', title: 'ThumbsUp', node: '170:9592', builder: _thumbsUp),
  GalleryEntry(group: 'atoms', title: 'TranslateToggle', node: '170:9624', builder: _translateToggle),
  GalleryEntry(group: 'atoms', title: 'ProgressBar', node: '175:12772', builder: _progressBar),
  GalleryEntry(group: 'atoms', title: 'Dim', node: '176:26363', builder: _dim),
  GalleryEntry(group: 'atoms', title: 'MicButton', builder: _micButton),
  GalleryEntry(group: 'atoms', title: 'RecordCircleButton', builder: _recordCircle),
  // ── molecules ──
  GalleryEntry(group: 'molecules', title: 'HeroAvatar', builder: _heroAvatar),
  GalleryEntry(group: 'molecules', title: 'RatingButton', builder: _ratingButton),
  GalleryEntry(group: 'molecules', title: 'OtpInput', builder: _otpInput),
  GalleryEntry(group: 'molecules', title: 'InputField', node: '175:8234', builder: _inputField),
  GalleryEntry(group: 'molecules', title: 'TextArea', node: '175:11371', builder: _textArea),
  GalleryEntry(group: 'molecules', title: 'Dropdown', node: '175:10075', builder: _dropdown),
  GalleryEntry(group: 'molecules', title: 'FieldValidation', node: '175:11301', builder: _fieldValidation),
  GalleryEntry(group: 'molecules', title: 'CountrySelect', node: '176:9989', builder: _countrySelect),
  GalleryEntry(group: 'molecules', title: 'SelectCard', node: '2291:21077', builder: _selectCard),
  GalleryEntry(group: 'molecules', title: 'CardLine', node: '176:15525', builder: _cardLine),
  GalleryEntry(group: 'molecules', title: 'CardBox', node: '176:15524', builder: _cardBox),
  GalleryEntry(group: 'molecules', title: 'CardAlarm', node: '176:20652', builder: _cardAlarm),
  GalleryEntry(group: 'molecules', title: 'ChatBubble', node: '176:21728', builder: _chatBubble),
  GalleryEntry(group: 'molecules', title: 'AvatarCard', node: '170:9627', builder: _avatarCard),
  GalleryEntry(group: 'molecules', title: 'PronunciationResult', node: '2224:20999', builder: _pronunciationResult),
  // ── organisms ──
  GalleryEntry(group: 'organisms', title: 'GNB', node: '162:46473', builder: _gnb),
  GalleryEntry(group: 'organisms', title: 'BottomNavBar', node: '164:441', builder: _bottomNav),
  GalleryEntry(group: 'organisms', title: 'DialogBasic', node: '175:12790', builder: _dialogBasic),
  GalleryEntry(group: 'organisms', title: 'DialogShareProfile', node: '2235:4652', builder: _dialogShare),
  GalleryEntry(group: 'organisms', title: 'BottomSheet', node: '175:18138', builder: _bottomSheet),
  GalleryEntry(group: 'organisms', title: 'BottomSheetDocument', node: '175:18500', builder: _bsDocument),
  // Superseded by AvatarDetail (`4024:1090`); kept for reference while the old
  // Figma master is still in the file. No screen calls it any more.
  GalleryEntry(group: 'organisms', title: 'BottomSheetAvatar (retired)', node: '176:13383', builder: _bsAvatar),
  GalleryEntry(group: 'organisms', title: 'AvatarDetail', node: '4024:1090', builder: _avatarDetail),
  GalleryEntry(group: 'organisms', title: 'BottomSheetCountrySelect', node: '176:12212', builder: _bsCountry),
  GalleryEntry(group: 'organisms', title: 'BottomSheetAlarmSettings', node: '176:13983', builder: _bsAlarm),
  GalleryEntry(group: 'organisms', title: 'BottomSheetFeedback', node: '176:15420', builder: _bsFeedback),
];

Widget _statusBar(BuildContext _) => const StatusBarDemo();
Widget _homeIndicator(BuildContext _) => const HomeIndicatorDemo();
Widget _button(BuildContext _) => const ButtonDemo();
Widget _checkbox(BuildContext _) => const CheckboxDemo();
Widget _toggle(BuildContext _) => const ToggleDemo();
Widget _iconButton(BuildContext _) => const AppIconButtonDemo();
Widget _selectBox(BuildContext _) => const SelectBoxDemo();
Widget _thumbsUp(BuildContext _) => const ThumbsUpDemo();
Widget _translateToggle(BuildContext _) => const TranslateToggleDemo();
Widget _progressBar(BuildContext _) => const ProgressBarDemo();
Widget _dim(BuildContext _) => const DimDemo();
Widget _inputField(BuildContext _) => const InputFieldDemo();
Widget _textArea(BuildContext _) => const TextAreaDemo();
Widget _dropdown(BuildContext _) => const DropdownDemo();
Widget _fieldValidation(BuildContext _) => const FieldValidationDemo();
Widget _countrySelect(BuildContext _) => const CountrySelectDemo();
Widget _selectCard(BuildContext _) => const SelectCardDemo();
Widget _cardLine(BuildContext _) => const CardLineDemo();
Widget _cardBox(BuildContext _) => const CardBoxDemo();
Widget _cardAlarm(BuildContext _) => const CardAlarmDemo();
Widget _chatBubble(BuildContext _) => const ChatBubbleDemo();
Widget _avatarCard(BuildContext _) => const AvatarCardDemo();
Widget _pronunciationResult(BuildContext _) => const PronunciationResultDemo();
Widget _gnb(BuildContext _) => const GnbDemo();
Widget _bottomNav(BuildContext _) => const BottomNavBarDemo();
Widget _dialogBasic(BuildContext _) => const DialogBasicDemo();
Widget _dialogShare(BuildContext _) => const DialogShareProfileDemo();
Widget _bottomSheet(BuildContext _) => const BottomSheetDemo();
Widget _bsDocument(BuildContext _) => const BottomSheetDocumentDemo();
Widget _bsAvatar(BuildContext _) => const BottomSheetAvatarDemo();
Widget _avatarDetail(BuildContext _) => const AvatarDetailDemo();
Widget _bsCountry(BuildContext _) => const BottomSheetCountrySelectDemo();
Widget _bsAlarm(BuildContext _) => const BottomSheetAlarmSettingsDemo();
Widget _bsFeedback(BuildContext _) => const BottomSheetFeedbackDemo();
Widget _micButton(BuildContext _) => const MicButtonDemo();
Widget _recordCircle(BuildContext _) => const RecordCircleButtonDemo();
Widget _heroAvatar(BuildContext _) => const HeroAvatarDemo();
Widget _ratingButton(BuildContext _) => const RatingButtonDemo();
Widget _otpInput(BuildContext _) => const OtpInputDemo();