"""국적 선택 국가 표 생성기 — lib/core/i18n/countries.g.dart 를 다시 쓴다(2026-10-10 · PM-DEC-490·495).

출처: tool/data/countries.json — 앱 서버 assets/countries.json · 웹 server/app/data/countries.json 과
같은 파일이다(249개 · CLDR 영문명 · 국적 모델 라벨 41개는 모델 표기). 세 곳이 같은 이름을 써야
서버가 보내는 actual_nationality 가 화면에서 고른 국가와 어긋나지 않는다. 표를 바꾸면 세 곳을 같이 바꾼다.

순서는 파일 순서 그대로(영어 알파벳순 · 웹과 같음). 국가명은 UI 언어와 무관하게 영어다(PM-DEC-490).

실행: PYTHONUTF8=1 python tool/gen_countries.py
"""
import io
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
data = json.load(io.open(ROOT / "tool" / "data" / "countries.json", encoding="utf-8"))
rows = list(data["en_by_iso"].items())
assert len(rows) == 249, len(rows)

out = io.StringIO()
out.write("// GENERATED by tool/gen_countries.py — 손으로 고치지 마라. 표를 바꾸면 서버·웹 countries.json 도 같이.\n")
out.write("// ignore_for_file: lines_longer_than_80_chars\n\n")
out.write("/// 국적 선택 목록 — (ISO 3166-1 alpha-2, 영어 국가명) 249개 · 영어 알파벳순.\n")
out.write("const List<(String, String)> kCountries = [\n")
for iso, name in rows:
    out.write(f"  ({json.dumps(iso)}, {json.dumps(name, ensure_ascii=False)}),\n")
out.write("];\n")
(ROOT / "lib" / "core" / "i18n" / "countries.g.dart").write_text(out.getvalue(), encoding="utf-8", newline="\n")
print("wrote", len(rows))
