"""억양 국적 이름표 생성기 — lib/core/i18n/country_names.dart 를 다시 쓴다.

출처: Unicode CLDR(파이썬 babel 패키지에 든 사본). 국적 라벨 41개는 서버
core/nationality.py 의 _LABEL_ISO 와 같아야 한다 — 서버가 라벨을 늘리면 여기도 늘린다.

실행: PYTHONUTF8=1 python tool/gen_country_names.py
"""
import io
import re

import babel
from babel import Locale

# 서버 core/nationality.py _LABEL_ISO(09-26 · 41개) + 취약발음 통계의 다른 표기.
LABEL_ISO = {
    "Bangladesh": "BD", "Brazil": "BR", "Bulgaria": "BG", "Cambodia": "KH",
    "Chile": "CL", "China": "CN", "Colombia": "CO", "Ethiopia": "ET",
    "France": "FR", "Germany": "DE", "Hong Kong": "HK", "India": "IN",
    "Indonesia": "ID", "Iran": "IR", "Italy": "IT", "Japan": "JP",
    "Kazakhstan": "KZ", "Korea": "KR", "Kyrgyzstan": "KG", "Malaysia": "MY",
    "Mongolia": "MN", "Myanmar": "MM", "Nepal": "NP", "Pakistan": "PK",
    "Peru": "PE", "Philippines": "PH", "Romania": "RO", "Russia": "RU",
    "Rwanda": "RW", "Singapore": "SG", "Spain": "ES", "Tajikistan": "TJ",
    "Thailand": "TH", "Turkey": "TR", "Turkmenistan": "TM", "Ukraine": "UA",
    "United Kingdom": "GB", "United States": "US", "Uzbekistan": "UZ",
    "Vietnam": "VN", "Zambia": "ZM",
    "Russian Federation": "RU",
}

LOCALES = ("ar bn de en es fi fil fr hi hu id it ja kk km ko ky mn ms my ne "
           "pt ru si th tr ur uz vi zh").split()

# CLDR 기본형은 「특별행정구」까지 붙은 공식명이다. babel 은 alt-short 를 안 싣는다 —
# 짧은 이름을 손으로 둔다.
HK_SHORT = {
    "ar": "هونغ كونغ", "bn": "হংকং", "de": "Hongkong", "en": "Hong Kong",
    "es": "Hong Kong", "fi": "Hongkong", "fil": "Hong Kong", "fr": "Hong Kong",
    "hi": "हाँग काँग", "hu": "Hongkong", "id": "Hong Kong", "it": "Hong Kong",
    "ja": "香港", "kk": "Гонконг", "km": "ហុងកុង", "ko": "홍콩", "ky": "Гонконг",
    "mn": "Хонг Конг", "ms": "Hong Kong", "my": "ဟောင်ကောင်", "ne": "हङकङ",
    "pt": "Hong Kong", "ru": "Гонконг", "si": "හොංකොං", "th": "ฮ่องกง",
    "tr": "Hong Kong", "ur": "ہانگ کانگ", "uz": "Gonkong", "vi": "Hồng Kông",
    "zh": "香港",
}

# 「Myanmar (Burma)」 류 괄호 설명은 뗀다.
PAREN = re.compile(r"\s*[(（][^)）]*[)）]\s*$")


def name(loc: str, iso: str) -> str:
    if iso == "HK":
        return HK_SHORT[loc]
    return PAREN.sub("", Locale.parse(loc).territories[iso])


def dart_str(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\'") + "'"


isos = sorted(set(LABEL_ISO.values()))
out = io.StringIO()
out.write(f"""// GENERATED by tool/gen_country_names.py — 손으로 고치지 말고 생성기를 고쳐 다시 돌린다.
// 출처: Unicode CLDR(babel {babel.__version__}). 홍콩만 짧은 이름을 손으로 둔다.

/// 국적 서버 라벨(영문 · 서버 `core/nationality.py` `_LABEL_ISO`) → ISO 3166-1 alpha-2.
const Map<String, String> kAccentLabelIso = {{
""")
for label, iso in LABEL_ISO.items():
    out.write(f"  {dart_str(label)}: {dart_str(iso)},\n")
out.write("};\n\n/// UI 언어 → ISO → 그 언어의 나라 이름.\nconst Map<String, Map<String, String>> kCountryNames = {\n")
for loc in LOCALES:
    out.write(f"  {dart_str(loc)}: {{\n")
    for iso in isos:
        out.write(f"    {dart_str(iso)}: {dart_str(name(loc, iso))},\n")
    out.write("  },\n")
out.write("};\n")
io.open("lib/core/i18n/country_names.g.dart", "w", encoding="utf-8", newline="\n").write(out.getvalue())
print("wrote", len(LOCALES), "locales x", len(isos), "countries")
